/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WineShopImport } from './routes/wineShop'
import { Route as WhereToBuyImport } from './routes/whereToBuy'
import { Route as VisitUsImport } from './routes/visitUs'
import { Route as OurWinesImport } from './routes/ourWines'
import { Route as AboutUsImport } from './routes/aboutUs'
import { Route as IndexImport } from './routes/index'
import { Route as WineWineIdImport } from './routes/wine/$wineId'

// Create/Update Routes

const WineShopRoute = WineShopImport.update({
  path: '/wineShop',
  getParentRoute: () => rootRoute,
} as any)

const WhereToBuyRoute = WhereToBuyImport.update({
  path: '/whereToBuy',
  getParentRoute: () => rootRoute,
} as any)

const VisitUsRoute = VisitUsImport.update({
  path: '/visitUs',
  getParentRoute: () => rootRoute,
} as any)

const OurWinesRoute = OurWinesImport.update({
  path: '/ourWines',
  getParentRoute: () => rootRoute,
} as any)

const AboutUsRoute = AboutUsImport.update({
  path: '/aboutUs',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WineWineIdRoute = WineWineIdImport.update({
  path: '/wine/$wineId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/aboutUs': {
      preLoaderRoute: typeof AboutUsImport
      parentRoute: typeof rootRoute
    }
    '/ourWines': {
      preLoaderRoute: typeof OurWinesImport
      parentRoute: typeof rootRoute
    }
    '/visitUs': {
      preLoaderRoute: typeof VisitUsImport
      parentRoute: typeof rootRoute
    }
    '/whereToBuy': {
      preLoaderRoute: typeof WhereToBuyImport
      parentRoute: typeof rootRoute
    }
    '/wineShop': {
      preLoaderRoute: typeof WineShopImport
      parentRoute: typeof rootRoute
    }
    '/wine/$wineId': {
      preLoaderRoute: typeof WineWineIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutUsRoute,
  OurWinesRoute,
  VisitUsRoute,
  WhereToBuyRoute,
  WineShopRoute,
  WineWineIdRoute,
])

/* prettier-ignore-end */
